### ISSUE TITLE
Error in Ext.CLIJ2_maximum3DSphere example ijm

### ISSUE THREAD

**Issue by quantixed** [clij/clij2-docs#27]
Hello, I can't get the example ijm for `Ext.CLIJ2_maximum3DSphere()` to run.

https://github.com/clij/clij2-docs/blob/8f34372ef33a856a3f831b914d80fcc3ccaf92db/src/main/macro/localMaximum.ijm#L30

```
Error:		Variable expected in line 30:
	
		Ext . CLIJ2_maximum3DSphere ( "original" , <"maximum3DSphereCLIJ_"> + radius , radius , radius , radius ) ; 
```

According to the source, this argument should be a destination image, but the error suggests it is expecting a variable.

--
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_172 [64-bit]; Mac OS X 10.16
CLIJ and CLIJ2 update sites installed and GPU speed test works.

**Comment by haesleinhuepf** [comment]
Hi @quantixed ,

good catch, thanks for reporting! This has something to do with a change in clij 2.5.3.4 in March 2020. [See this commit](https://github.com/clij/clij2/commit/e99d316f0de89e6e1a82f61614278c1e357f7c68). Since then, output images must be variables. I updated the example accordingly: https://github.com/clij/clij2-docs/blob/master/src/main/macro/localMaximum.ijm

Let me know if the new example doesn't work for you.
